services:
  lasallian-me-oss:
    build: .
    ports:
      - "3000:3000"
    environment:
      - IMAGE_STORE_PATH: ${IMAGE_STORE_PATH}
      - CLIENT_SECRET_KEY: ${CLIENT_SECRET_KEY}
      - MONGODB_URI: ${MONGODB_URI}
    volumes:
      - oss-images:/${IMAGE_STORE_PATH}

volumes:
  oss-images:
